version: "3.7"

networks:
  frontend:
  backend:

services:

  dbapp:
    container_name: "lnmp-dbapp"
    image: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend
    ports:
      - 3306:3306

  php:
    container_name: "lnmp-php"
    build:
      context: .docker/php
      network: host
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    restart: unless-stopped
    depends_on:
      - dbapp
    volumes:
      - "./:/web/"
    environment:
      docker: "true"
    networks:
      - backend
    ports:
      - 9000:9000

  nginx:
    container_name: "lnmp-nginx"
    build:
      context: .docker/nginx
      network: host
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    depends_on:
      - php
      - dbapp
    restart: unless-stopped
    volumes:
      - "./:/web/"
    networks:
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443
