version: "3.7"

networks:
  frontend:
  backend:

volumes:
  mysql_data:

services:

  mysql:
    container_name: "lemp-mysql"
    image: mysql
    restart: unless-stopped
    volumes:
      - "mysql_data:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD:?Unspecified MYSQL_ROOT_PASSWORD variable}
      MYSQL_USER:           ${MYSQL_USER:?Unspecified MYSQL_USER variable}
      MYSQL_PASSWORD:       ${MYSQL_PASSWORD:?Unspecified MYSQL_PASSWORD variable}
      MYSQL_DATABASE:       ${MYSQL_DATABASE:?Unspecified MYSQL_DATABASE variable}
    networks:
      - backend
    ports:
      - 3306:3306

  php:
    container_name: "lemp-php"
    build:
      context: .docker/php
      network: host
      args:
        DC_USER_ID: ${DC_USER_ID:-0}
        DC_GROUP_ID: ${DC_GROUP_ID:-0}
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - "./:/web/"
    environment:
      docker: "true"
    networks:
      - backend

  nginx:
    container_name: "lemp-nginx"
    build:
      context: .docker/nginx
      network: host
    depends_on:
      - php
      - mysql
    restart: unless-stopped
    volumes:
      - "./:/web/"
      - ".docker/nginx/conf.d/:/etc/nginx/conf.d/"
    networks:
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443
