version: '3.7'

services:

  adminer:
    container_name: "lnmp-adminer"
    image: adminer
    restart: unless-stopped
    depends_on:
        - dbapp
    networks:
      - backend
    ports:
      - 8080:8080